In [4]:
import numpy as np
orig_array = np.array([[[1,2],
                        [3,4]],
                        
                        [[5,6],
                        [7,8]],
                        
                        [[9,10],
                        [11,12]],
                         
                        [[13,14],
                        [15,16]]])
orig_array.shape

(4, 2, 2)

In [37]:
array = orig_array.reshape(16,1,1)

In [38]:
array = array.reshape(4,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
array = array.reshape(4,2,2)

In [40]:
array = array.swapaxes(0,1)

In [41]:
array = array.reshape(4,4)
array

array([[ 1,  2,  5,  6],
       [ 9, 10, 13, 14],
       [ 3,  4,  7,  8],
       [11, 12, 15, 16]])

In [42]:
array[[1,2]] = array[[2,1]]

In [43]:
array

array([[ 1,  2,  5,  6],
       [ 3,  4,  7,  8],
       [ 9, 10, 13, 14],
       [11, 12, 15, 16]])